// Creacion de Array con el constructor
const celulares = [
    {
        "marca": "Iphone",
        "modelo": "11",
        "so": "IOS",
        "pantalla": "5.8",
        "color": "Blanco",
        "camara": "12MP",
        "precio": "279999",
        "stock": "3",
        "fotofront": "assets/iphone11front.jpg",
        "fotoback": "assets/iphone11front.jpg"
    },
    {
        "marca": "Iphone",
        "modelo": "11",
        "so": "IOS",
        "pantalla": "5.8",
        "color": "Negro",
        "camara": "12MP",
        "precio": "279999",
        "stock": "3",
        "fotofront": "assets/iphone11front.jpg",
        "fotoback": "assets/iphone11front.jpg"
    },
    {
        "marca": "LG",
        "modelo": "K50",
        "so": "Android",
        "pantalla": "6.26",
        "color": "Negro",
        "camara": "13MP",
        "precio": "19999",
        "stock": "3",
        "fotofront": "assets/lgk50fotofront.jpg",
        "fotoback": "assets/lgk50fotoback.jpg"
    },
    {
        "marca": "LG",
        "modelo": "Velvet",
        "so": "Android",
        "pantalla": "6.8",
        "color": "Negro",
        "camara": "48MP",
        "precio": "69999",
        "stock": "3",
        "fotofront": "assets/LGvelvetfront.jpg",
        "fotoback": "assets/LGvelvetback.jpg"
    },
    {
        "marca": "LG",
        "modelo": "Velvet",
        "so": "Android",
        "pantalla": "6.8",
        "color": "Rojo",
        "camara": "48MP",
        "precio": "69999",
        "stock": "3",
        "fotofront": "assets/LGvelvetfront.jpg",
        "fotoback": "assets/LGvelvetback.jpg"
    },
    {
        "marca": "Motorola",
        "modelo": "Edge",
        "so": "Android",
        "pantalla": "6.67",
        "color": "Negro",
        "camara": "64MP",
        "precio": "89999",
        "stock": "3",
        "fotofront": "assets/motorolaedgefront.jpg",
        "fotoback": "assets/motorolaedgeback.jpg"
    },
    {
        "marca": "Motorola",
        "modelo": "Edge",
        "so": "Android",
        "pantalla": "6.67",
        "color": "Azul",
        "camara": "64MP",
        "precio": "89999",
        "stock": "3",
        "fotofront": "assets/motorolaedgefront.jpg",
        "fotoback": "assets/motorolaedgeback.jpg"
    },
    {
        "marca": "Motorola",
        "modelo": "G9",
        "so": "Android",
        "pantalla": "6.78",
        "color": "Azul",
        "camara": "64MP",
        "precio": "35999",
        "stock": "3",
        "fotofront": "assets/motorolag9powerfront.jpg",
        "fotoback": "assets/motorolag9powerback.jpg"
    },
    {
        "marca": "Samsung",
        "modelo": "A31",
        "so": "Android",
        "pantalla": "6.4",
        "color": "Azul",
        "camara": "48MP",
        "precio": "39999",
        "stock": "3",
        "fotofront": "assets/samsungA31.jpg",
        "fotoback": "assets/samsungA31back.jpg"
    },
    {
        "marca": "Samsung",
        "modelo": "A51",
        "so": "Android",
        "pantalla": "6.5",
        "color": "Azul",
        "camara": "48MP",
        "precio": "45999",
        "stock": "3",
        "fotofront": "assets/samsungA51front.jpg",
        "fotoback": "assets/samsungA51back.jpg"
    },
    {
        "marca": "Samsung",
        "modelo": "A51",
        "so": "Android",
        "pantalla": "6.5",
        "color": "Negro",
        "camara": "48MP",
        "precio": "45999",
        "stock": "3",
        "fotofront": "assets/samsungA51front.jpg",
        "fotoback": "assets/samsungA51back.jpg"
    },
    {
        "marca": "Xiaomi",
        "modelo": "Note 10",
        "so": "Android",
        "pantalla": "6.47",
        "color": "Blanco",
        "camara": "64MP",
        "precio": "94999",
        "stock": "3",
        "fotofront": "assets/xiaomiminote10front.jpg",
        "fotoback": "assets/xiaomiminote10back.jpg"
    },
    {
        "marca": "Xiaomi",
        "modelo": "Redmi 9s",
        "so": "Android",
        "pantalla": "6.7",
        "color": "Negro",
        "camara": "48MP",
        "precio": "54999",
        "stock": "3",
        "fotofront": "assets/xiaomiredminote9sfront.jpg",
        "fotoback": "assets/xiaomiredminote9sfront.jpg"
    },
    {
        "marca": "Xiaomi",
        "modelo": "Redmi 9s",
        "so": "Android",
        "pantalla": "6.7",
        "color": "Blanco",
        "camara": "48MP",
        "precio": "54999",
        "stock": "3",
        "fotofront": "assets/xiaomiredminote9sfront.jpg",
        "fotoback": "assets/xiaomiredminote9sfront.jpg"
    }
];
